CREATE TABLE GORZYNSKIM.departments AS SELECT * FROM hr.departments;
CREATE TABLE GORZYNSKIM.countries AS SELECT * FROM hr.countries;
CREATE TABLE GORZYNSKIM.employees AS SELECT * FROM hr.employees;
CREATE TABLE GORZYNSKIM.jobs AS SELECT * FROM hr.jobs;
CREATE TABLE GORZYNSKIM.job_grades AS SELECT * FROM hr.job_grades;
CREATE TABLE GORZYNSKIM.job_history AS SELECT * FROM hr.job_history;
CREATE TABLE GORZYNSKIM.locations AS SELECT * FROM hr.locations;
CREATE TABLE GORZYNSKIM.regions AS SELECT * FROM hr.regions;

ALTER TABLE GORZYNSKIM.REGIONS
ADD CONSTRAINT PK_REGIONS PRIMARY KEY (REGION_ID);

ALTER TABLE GORZYNSKIM.COUNTRIES
ADD CONSTRAINT PK_COUNTRIES PRIMARY KEY (COUNTRY_ID);

ALTER TABLE GORZYNSKIM.COUNTRIES
ADD CONSTRAINT FK_COUNTRIES_REGION
FOREIGN KEY (REGION_ID) REFERENCES GORZYNSKIM.REGIONS(REGION_ID);

ALTER TABLE GORZYNSKIM.LOCATIONS
ADD CONSTRAINT PK_LOCATIONS PRIMARY KEY (LOCATION_ID);

ALTER TABLE GORZYNSKIM.LOCATIONS
ADD CONSTRAINT FK_LOCATIONS_COUNTRY
FOREIGN KEY (COUNTRY_ID) REFERENCES GORZYNSKIM.COUNTRIES(COUNTRY_ID);

ALTER TABLE GORZYNSKIM.DEPARTMENTS
ADD CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (DEPARTMENT_ID);

ALTER TABLE GORZYNSKIM.DEPARTMENTS
ADD CONSTRAINT FK_DEPARTMENTS_LOCATION
FOREIGN KEY (LOCATION_ID) REFERENCES GORZYNSKIM.LOCATIONS(LOCATION_ID);

ALTER TABLE GORZYNSKIM.JOBS
ADD CONSTRAINT PK_JOBS PRIMARY KEY (JOB_ID);

ALTER TABLE GORZYNSKIM.EMPLOYEES
ADD CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPLOYEE_ID);

ALTER TABLE GORZYNSKIM.EMPLOYEES
ADD CONSTRAINT FK_EMPLOYEES_MANAGER
FOREIGN KEY (MANAGER_ID) REFERENCES GORZYNSKIM.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE GORZYNSKIM.EMPLOYEES
ADD CONSTRAINT FK_EMPLOYEES_DEPARTMENT
FOREIGN KEY (DEPARTMENT_ID) REFERENCES GORZYNSKIM.DEPARTMENTS(DEPARTMENT_ID);

ALTER TABLE GORZYNSKIM.EMPLOYEES
ADD CONSTRAINT FK_EMPLOYEES_JOB
FOREIGN KEY (JOB_ID) REFERENCES GORZYNSKIM.JOBS(JOB_ID);

ALTER TABLE GORZYNSKIM.JOB_HISTORY
ADD CONSTRAINT PK_JOB_HISTORY
PRIMARY KEY (EMPLOYEE_ID, START_DATE);

ALTER TABLE GORZYNSKIM.JOB_HISTORY
ADD CONSTRAINT FK_JOB_HISTORY_EMPLOYEE
FOREIGN KEY (EMPLOYEE_ID) REFERENCES GORZYNSKIM.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE GORZYNSKIM.JOB_HISTORY
ADD CONSTRAINT FK_JOB_HISTORY_JOB
FOREIGN KEY (JOB_ID) REFERENCES GORZYNSKIM.JOBS(JOB_ID);

ALTER TABLE GORZYNSKIM.JOB_HISTORY
ADD CONSTRAINT FK_JOB_HISTORY_DEPARTMENT
FOREIGN KEY (DEPARTMENT_ID) REFERENCES GORZYNSKIM.DEPARTMENTS(DEPARTMENT_ID);

ALTER TABLE GORZYNSKIM.JOB_GRADES
ADD CONSTRAINT PK_JOB_GRADES PRIMARY KEY (GRADE);

-- TWORZENIE WIDOKOW

ALTER SESSION SET CURRENT_SCHEMA = GORZYNSKIM;

CREATE VIEW WIDOK1 AS
SELECT LAST_NAME AS "NAZWISKO", SALARY AS "WYNAGRODZENIE"
FROM EMPLOYEES WHERE DEPARTMENT_ID IN (20, 50) AND SALARY BETWEEN 2000 AND 7000
ORDER BY LAST_NAME;

CREATE VIEW WIDOK2 AS
SELECT HIRE_DATE AS "DATA ZATRUDNIENIA", LAST_NAME AS "NAZWISKO", EMAIL AS "EMAIL"
FROM EMPLOYEES
WHERE MANAGER_ID IN (
    SELECT EMPLOYEE_ID
    FROM EMPLOYEES
    WHERE EXTRACT(YEAR FROM HIRE_DATE) = 2005
)
ORDER BY EMAIL;

CREATE VIEW WIDOK3 AS
SELECT FIRST_NAME || ' ' || LAST_NAME AS "IMIE_NAZWISKO", SALARY AS "ZAROBKI", PHONE_NUMBER AS "NUMER_TELEFONU"
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%e%' AND FIRST_NAME LIKE '%aw%'
ORDER BY 1 DESC, 2;

CREATE VIEW WIDOK4 AS
SELECT FIRST_NAME, LAST_NAME, 
       ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) AS "LICZBA_MIES",
       CASE
           WHEN ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) <= 150 THEN 0.10 * SALARY
           WHEN ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) > 150 AND ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) <= 200 THEN 0.20 * SALARY
           ELSE 0.30 * SALARY
       END AS "WYS_DODATKU"
FROM EMPLOYEES
ORDER BY "LICZBA_MIES";

CREATE VIEW WIDOK5 AS
SELECT DEPARTMENT_ID, 
       SUM(SALARY) AS "SUMA_ZAROBKOW",
       ROUND(AVG(SALARY)) AS "SREDNIA_ZAROBKOW"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING MIN(SALARY) > 5000;

CREATE VIEW WIDOK6 AS
SELECT EMPLOYEES.LAST_NAME, DEPARTMENTS.DEPARTMENT_ID AS NUMER_DEP,
       DEPARTMENTS.DEPARTMENT_NAME AS NAZWA_DEP, EMPLOYEES.JOB_ID AS PRACA_ID,
       LOCATIONS.CITY AS MIASTO
FROM EMPLOYEES
JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
WHERE LOCATIONS.CITY = 'Toronto';

CREATE VIEW Widok7 AS
SELECT E1.FIRST_NAME AS "IMIE",
       E1.LAST_NAME AS "NAZWISKO",
       E2.FIRST_NAME AS "IMIE_WSPOLPRACOWNIKA",
       E2.LAST_NAME AS "NAZWISKO_WSPOLPRACOWNIKA"
FROM EMPLOYEES E1
JOIN EMPLOYEES E2 ON E1.EMPLOYEE_ID = E2.MANAGER_ID
WHERE E1.FIRST_NAME = 'Jennifer';

CREATE VIEW WIDOK8 AS
SELECT DEPARTMENT_ID
FROM DEPARTMENTS
WHERE DEPARTMENT_ID NOT IN (
    SELECT DISTINCT DEPARTMENT_ID
    FROM EMPLOYEES
);

--CREATE TABLE JOB_GRADES AS
--SELECT * FROM HR.JOB_GRADES;

CREATE VIEW WIDOK9 AS
SELECT FIRST_NAME, LAST_NAME, JOB_ID, SALARY, GRADE
FROM EMPLOYEES E
JOIN JOB_GRADES JG ON E.JOB_ID = JG.JOB_ID;

CREATE VIEW WIDOK10 AS
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM GORZYNSKIM.EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES)
ORDER BY SALARY DESC;

CREATE VIEW WIDOK11 AS
SELECT E.EMPLOYEE_ID AS "ID", E.FIRST_NAME AS "IMIE", E.LAST_NAME AS "NAZWISKO"
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID IN (
    SELECT DISTINCT E2.DEPARTMENT_ID
    FROM EMPLOYEES E2
    WHERE E2.LAST_NAME LIKE '%u%'
);












